### ISSUE TITLE
Exception on attempting to submit bookmark

### ISSUE THREAD

**Issue by sknebel** [aaronpk/IndieNews#53]
Using the form on https://news.indieweb.org/en/submit with https://www.svenknebel.de/posts/2021/5/4/ leads to an error page:

```
Type: ErrorException
Code: 8
Message: Trying to access array offset on value of type null
File: /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Formats/Mf2.php
Line: 411
Trace

#0 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Formats/Mf2.php(411): Slim\Slim::handleErrors()
#1 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Formats/Mf2.php(456): p3k\XRay\Formats\Mf2::determineNameAndContent()
#2 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Formats/Mf2.php(48): p3k\XRay\Formats\Mf2::parseAsHEntry()
#3 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Formats/HTML.php(142): p3k\XRay\Formats\Mf2::parse()
#4 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Parser.php(81): p3k\XRay\Formats\HTML::parse()
#5 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay.php(38): p3k\XRay\Parser->parse()
#6 /web/sites/news.indieweb.org/controllers/webmention.php(104): p3k\XRay->parse()
#7 [internal function]: {closure}()
#8 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Router.php(172): call_user_func_array()
```

The markup on that page is not perfectly beautiful, but should IMHO pass.

**Comment by fluffy-critter** [comment]
I ran into a similar issue trying to submit https://beesbuzz.biz/blog/chatter/1587-Small-Web using pushl:

```
INFO:pushl.webmentions:https://news.indieweb.org/en/webmention: mention of https://beesbuzz.biz/blog/chatter/1587-Small-Web -> https://news.indieweb.org/en failed: <html><head><title>Slim Application Error</title><style>body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif;}h1{margin:0;font-size:48px;font-weight:normal;line-height:48px;}strong{display:inline-block;width:65px;}</style></head><body><h1>Slim Application Error</h1><p>The application could not run because of the following error:</p><h2>Details</h2><div><strong>Type:</strong> ErrorException</div><div><strong>Code:</strong> 8</div><div><strong>Message:</strong> Trying to access array offset on value of type null</div><div><strong>File:</strong> /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Formats/Mf2.php</div><div><strong>Line:</strong> 411</div><h2>Trace</h2><pre>#0 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Formats/Mf2.php(411): Slim\Slim::handleErrors()
#1 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Formats/Mf2.php(456): p3k\XRay\Formats\Mf2::determineNameAndContent()
#2 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Formats/Mf2.php(48): p3k\XRay\Formats\Mf2::parseAsHEntry()
#3 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Formats/HTML.php(142): p3k\XRay\Formats\Mf2::parse()
#4 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay/Parser.php(81): p3k\XRay\Formats\HTML::parse()
#5 /web/sites/news.indieweb.org/vendor/p3k/xray/lib/XRay.php(38): p3k\XRay\Parser->parse()
#6 /web/sites/news.indieweb.org/controllers/webmention.php(104): p3k\XRay->parse()
#7 [internal function]: {closure}()
#8 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Router.php(172): call_user_func_array()
#9 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Slim.php(1222): Slim\Router->dispatch()
#10 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#11 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#12 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#13 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Slim.php(1174): Slim\Middleware\PrettyExceptions->call()
#14 /web/sites/news.indieweb.org/public/index.php(31): Slim\Slim->run()
#15 {main}</pre></body></html>
```

I have submitted bookmarks in this exact same way before ([example post](https://news.indieweb.org/en/atthis.link/blog/2021/rss.html)), so I have no idea what's different now.
