### ISSUE TITLE
Crash in CASSIS

### ISSUE THREAD

**Issue by snarfed** [aaronpk/IndieNews#61]
Filing to track: feed pages (eg https://news.indieweb.org/en ) are currently crashing with this stack trace. May have been caused by submitting https://snarfed.org/2023-10-13_51135 , not sure yet. cc @tantek

```
Slim Application Error

The application could not run because of the following error:
Details
Type: ErrorException
Code: 8
Message: Uninitialized string offset: 0
File: /web/sites/news.indieweb.org/vendor/tantek/cassis/cassis.php
Line: 118
Trace

#0 /web/sites/news.indieweb.org/vendor/tantek/cassis/cassis.php(118): Slim\Slim::handleErrors()
#1 /web/sites/news.indieweb.org/views/_post-row.php(6): auto_link()
#2 /web/sites/news.indieweb.org/lib/Savant3/Savant3.php(1074): include('/web/sites/news...')
#3 /web/sites/news.indieweb.org/lib/Savant3/Savant3.php(1006): Savant3->fetch()
#4 /web/sites/news.indieweb.org/lib/Savant3/Savant3.php(993): Savant3->getOutput()
#5 /web/sites/news.indieweb.org/lib/helpers.php(111): Savant3->display()
#6 /web/sites/news.indieweb.org/views/posts.php(12): partial()
#7 /web/sites/news.indieweb.org/lib/Savant3/Savant3.php(1074): include('/web/sites/news...')
#8 /web/sites/news.indieweb.org/views/layout.php(60): Savant3->fetch()
#9 /web/sites/news.indieweb.org/lib/Savant3/Savant3.php(1074): include('/web/sites/news...')
#10 /web/sites/news.indieweb.org/lib/Savant.php(74): Savant3->fetch()
#11 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/View.php(195): Slim\Extras\Views\Savant->render()
#12 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/View.php(182): Slim\View->fetch()
#13 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Slim.php(672): Slim\View->display()
#14 /web/sites/news.indieweb.org/lib/helpers.php(94): Slim\Slim->render()
#15 /web/sites/news.indieweb.org/controllers/controllers.php(59): render()
#16 [internal function]: {closure}()
#17 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Router.php(172): call_user_func_array()
#18 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Slim.php(1222): Slim\Router->dispatch()
#19 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#20 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#21 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#22 /web/sites/news.indieweb.org/vendor/slim/slim/Slim/Slim.php(1174): Slim\Middleware\PrettyExceptions->call()
#23 /web/sites/news.indieweb.org/public/index.php(31): Slim\Slim->run()
#24 {main}
```

**Comment by aaronpk** [comment]
This does appear to be a bug in cassis. I tracked it down and filed an issue:

https://github.com/tantek/cassis/issues/43

**Comment by aaronpk** [comment]
This has been fixed in the latest version of cassis
